#
# 50M scaling experiment on LUMI.
#

###############################################################
# AUTOEXP.
# Special variables used by autoexp.

autoexp:

    # Helpers and cluster setup script.
    oellm_folder: "/scratch/project_462000963/users/donutu/autoexperiment/oellm"
    helpers: "{oellm_folder}/helpers"
    cluster: "{oellm_folder}/cluster"

    # Output folder. For this example we write in this folder.
    out_folder: "/scratch/project_462000963/users/donutu/oellm_scaling"
    logs: "{out_folder}/logs"
    ckpts: "{out_folder}/ckpts"
    scripts: "{out_folder}/sbatch"

    # Templated sbatch.
    template: "/scratch/project_462000963/users/donutu/autoexperiment/scripts/dense/test_lumi/train.sbatch"

    # Destination for sbatch script and command to execute.
    sbatch_script: "{scripts}/{name}.sbatch"
    cmd: "sbatch {sbatch_script}"

    # Termination cmd.
    termination_cmd: "{helpers}/finished_train.py {logs} {slurm.job_name}"

###############################################################
# TEMPLATE ARGS.
# Placeholders in the templated sbatch.

slurm:

    job_name: "{autoexp.name}"
    out_dir: "{autoexp.logs}"
    ckpt_dir: "{autoexp.ckpts}"

    account: "project_462000963"
    partition: small-g

    cluster_setup_script: "{autoexp.cluster}/setup_lumi.sh"

###############################################################
# MEGATRON ARGS.
# These args are concatenated and passed verbatim to Megatron-LM.

args:

    # wandb name
    wandb_exp_name: "{autoexp.name}"
    wandb_project: warmup-test-50M

    # DATA
    data_path: [
      /scratch/project_462000963/preprocessed/gpt-neox-20b/nemotron-cc/1.0/high-actual,
      /scratch/project_462000963/preprocessed/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-distill,
      /scratch/project_462000963/preprocessed/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-diverse_qa_pairs,
      /scratch/project_462000963/preprocessed/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-extract_knowledge,
      /scratch/project_462000963/preprocessed/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-knowledge_list,
      /scratch/project_462000963/preprocessed/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-wrap_medium  
    ]
    seq_length: 4096
    max_position_embeddings: 4096
    tokenizer_model: EleutherAI/gpt-neox-20b
    tokenizer_type: HuggingFaceTokenizer
    num_workers: 8
    num-dataset-builder-threads: 6 # lumi-specific
    split: '99,1,0'

    # MODEL
    num_layers: 12
    hidden_size: 384
    ffn_hidden_size: 1536
    num_attention_heads: 6
    init_method_std: 0.02
    position_embedding_type: "rope"
    rotary_base: 10000
    rotary_percent: 1.0
    group_query_attentions: False
    num_query_groups: 6 # no gqa when NUM_QUERY_GROUPS==NUM_ATTENTION_HEADS TODO: check
    attention_dropout: 0.0
    hidden_dropout: 0.0
    normalization: RMSNorm
    norm_epsilon: 1.e-5 # rmsnorm epsilon
    qk_layernorm: True # potentially enable qk-norm
    bf16: True
    swiglu: True
    untie_embeddings_and_output_weights: False
    use_flash_attn: True
    attention_softmax_in_fp32: False # OpenSci style
    disable_bias_linear: False

    # TRAINING, PARALLELISM
    recompute_activations: False
    use_torch_fsdp2: False # it's either this or the next 4 args
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    context_parallel_size: 1
    sequence_parallel: True

    distributed_backend: nccl
    distributed_timeout_minutes: 10

    # DISTRIBUTED OPTIM: False, since (1) small model, (2) troubles with resuming, TODO: fix.
    use_distributed_optimizer: False

    # OPTIMIZER
    optimizer: adam
    adam_beta1: 0.9
    adam_beta2: 0.99
    adam_eps: 1.e-8
    clip_grad: 1.0
    weight_decay: 0.1

    # SCHEDULER
    min_lr: 0.0
    lr_decay_style: WSD
    lr_wsd_decay_style: linear
    # lr_warmup_iters: 1000 # For now we fix it to 1k

    # PROFILE
    profile: False
    use_pytorch_profiler: False
    profile_ranks: [0]
    profile_step_start: 5
    profile_step_end: 12

    # EVALS
    eval_interval: 5000
    eval_iters: 100

    # LOGGING
    log_interval: 10
    log_progress: True
    log_throughput: True
    tensorboard_queue_size: 5

    # Set CHECKPOINT_FORMAT
    ckpt_format: "torch" # "torch_dist" is bugged, TODO: fix
    save_interval: 500

    # LUMI-specific configs
    te-fallback-layernorm-linear: True 
    no-bias-swiglu-fusion: True 
    no-bias-dropout-fusion: True 
    no-gradient-accumulation-fusion: True

###############################################################
# EXPERIMENT SECTION.
# Here we define the sweep, varying LR, BSZ, NODES, GPUS, and phases (stable, decay).
# We can set and refer to autoexp args, by prepending `autoexp.`.
# We can set and refer to slurm args, by prepending `slurm.`.
# We can set and refer to megatron args, by prepending `args.`.

experiments:

    # A base name common to all phases.
    base_name: "50M_lr{args.lr}_gbsz{args.global_batch_size}"

    # Batch size per gpu.
    args.micro_batch_size: 16

    # Learning rate sweep.
    args.lr: [5.e-4, 1.e-3, 2.e-3, 4.e-3, 8.e-3]

    # Warmup sweep.
    warmup_fractpion: [1, 5, 10, 20]
    args.lr_warmup_iters: "expr(int(({warmup_fractpion} / 100) * {args.train_iters}))"

    # Sweep over global batch sizes and corresponding nodes/gpus.
    sweep:
        # - full_node:
        #     args.global_batch_size: [64, 128, 256, 512]
        #     slurm.gpus_per_node: 4
        #     slurm.nodes: "expr({args.global_batch_size} // ({args.micro_batch_size} * {slurm.gpus_per_node}))"

        - half_node:
            args.global_batch_size: 512
            slurm.gpus_per_node: 8
            slurm.nodes: 2

    # Train iters from tokens
    args.train_iters: "expr(({tokens} + {args.seq_length} * {args.global_batch_size} - 1) // ({args.seq_length} * {args.global_batch_size}))"
    
    # Stable and cooldowns
    phase:
        # - stable:
        #     autoexp.name: "{base_name}_stable"
        #     tokens: 50_000_000_000
        #     args.lr_wsd_decay_iters: 0

        - decay:
            autoexp.name: "{base_name}_decay{args.train_iters}_wu{args.lr_warmup_iters}"
            scale:
            - 6B:
                tokens: 6_000_000_000
            # - 12B:
            #     tokens: 12_000_000_000
            # - 30B:
            #     tokens: 30_000_000_000
            # - 50B:
            #     tokens: 50_000_000_000

            # Cooldown 20%, start cooldown at 80% of train_iters.
            decay_fraction: 0.2
            start_iter: "expr(int({args.train_iters} * (1 - {decay_fraction})))"

            # Round down to the previous number to a multiple of 500 (save_interval).
            start_iter_round: "expr(int(({start_iter} + 250) // 500 * 500))"

            # Decay iterations
            args.lr_wsd_decay_iters: "expr(int({args.train_iters} * {decay_fraction}))"

            # # Start decay when the stable run has reached start_iter.
            # autoexp.start_condition_cmd: "{autoexp.helpers}/pending_cooldown.py \
            #     {autoexp.ckpts} {base_name}_stable {autoexp.name} {start_iter_round}"

            # Override the LR Scheduler in the decay phase.
            args.override_opt_param_scheduler: True
